#!/bin/sh

userdel -rf $1

# userdel - удаляет регистрационное имя пользователя из системы
# -r - удаление домашнего каталога пользователя и почтового ящика
# -f, --force
#  This option forces the removal of the user account, even if the user is still logged in. It also forces userdel to remove the user's home directory and mail spool, even if another user uses the same home directory or if the mail spool is not owned by the specified user.
